# Generated by Django 5.1.2 on 2026-03-25 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cgv', 'CGV'), ('cookies', 'Cookies Policy'), ('legal_mentions', 'Legal Mentions'), ('privacy_policy', 'Privacy Policy')], max_length=20)),
                ('version', models.CharField(help_text='Ex: 2024-06-01', max_length=20, validators=[django.core.validators.RegexValidator(message='Version format must be YYYY-MM-DD.', regex='^\\d{4}-\\d{2}-\\d{2}$')])),
                ('content_fr', models.TextField(default='')),
                ('content_en', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('document_type', 'version')},
            },
        ),
    ]
