# Generated by Django 5.1.2 on 2026-03-25 09:21

from django.db import migrations


def rename_cgv_to_terms(apps, schema_editor):
    LegalDocument = apps.get_model('legal', 'LegalDocument')
    LegalDocument.objects.filter(document_type='cgv').update(document_type='terms')

class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_migrate_legal_documents'),
    ]

    operations = [
        migrations.RunPython(rename_cgv_to_terms),
    ]