"""
Django settings for web_shop project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import environ
import os
from django.utils.translation import gettext_lazy as _




env = environ.Env(
    DEBUG=(bool, False)  # Par défaut, DEBUG sera False
)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Path(__file__).resolve().parent.parent

# Lisez le fichier .env
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

DJANGO_ENV = env('DJANGO_ENV')

IS_PROD = DJANGO_ENV == 'production'

IS_TEST = DJANGO_ENV == 'test'

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])


# Application definition

INSTALLED_APPS = [
    # Native
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',

    # Third-party
    'csp',
    'django_extensions',

    # My apps
    'page_vente',
    'core',
    'legal',
]

if not IS_TEST:
    INSTALLED_APPS += ['cloudinary', 'cloudinary_storage']


LANGUAGES = [
    ('fr', _('Français')),
    ('en', _('English')),
]

LANGUAGE_CODE = 'fr'  # Langue par défaut

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'web_shop.middleware.CustomRequestMiddleware',
]

ROOT_URLCONF = 'web_shop.urls'

CLIENT_PHONE_NUMBER = env('CLIENT_PHONE_NUMBER', default='Non disponible')
CLIENT_EMAIL=env('CLIENT_EMAIL',default='Non disponible')
CLIENT_INSTAGRAM = env('CLIENT_INSTAGRAM', default='Non disponible')
CLIENT_FACEBOOK = env('CLIENT_FACEBOOK', default='Non disponible')

def global_variables(request):
    return {
        'CLIENT_PHONE_NUMBER': CLIENT_PHONE_NUMBER,
        'CLIENT_EMAIL': CLIENT_EMAIL,
        'CLIENT_INSTAGRAM': CLIENT_INSTAGRAM,
        'CLIENT_FACEBOOK': CLIENT_FACEBOOK,
    }
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'web_shop.settings.global_variables', # rendre les variables de .env disponibles dans les templates
            ],
        },
    },
]

WSGI_APPLICATION = 'web_shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': env.db(),
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STORAGES = {
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if IS_TEST else
            "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
        )
    },
}

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Dossier où Django va collecter les fichiers statiques
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'page_vente/static'), 
    os.path.join(BASE_DIR, 'core/static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'  # Peut permettre certaines interactions externes
SECURE_CROSS_ORIGIN_RESOURCE_POLICY = 'same-origin'  # Permet de charger des ressources locales


# ── Sécurité ────────────────────────────────────────────────────────────────
SESSION_COOKIE_SECURE = IS_PROD
CSRF_COOKIE_SECURE    = IS_PROD
SECURE_SSL_REDIRECT   = IS_PROD
SECURE_HSTS_SECONDS   = 31536000 if IS_PROD else 0
SECURE_BROWSER_XSS_FILTER      = True
CSRF_COOKIE_HTTPONLY            = True
X_FRAME_OPTIONS                 = 'DENY'
SESSION_COOKIE_SAMESITE         = 'Lax'
CSRF_COOKIE_SAMESITE            = 'Lax'
SECURE_REFERRER_POLICY          = 'strict-origin'
SECURE_CONTENT_TYPE_NOSNIFF     = IS_PROD

if IS_PROD:
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD            = True
    CSP_DEFAULT_SRC = ("'self'",)
    CSP_SCRIPT_SRC  = ("'self'",)
    CSP_IMG_SRC     = ("'self'", "https://res.cloudinary.com", "https://www.leatherworkintravelingdb.com")
elif not IS_TEST:  # development
    CSP_DEFAULT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'", "http://localhost:*", "ws://localhost:*", "http://127.0.0.1")
    CSP_IMG_SRC     = ("'self'", "https://res.cloudinary.com")

# ── Services externes (inutiles en test) ────────────────────────────────────
if not IS_TEST:
    import cloudinary

    cloudinary.config(
        cloud_name    = env('CLOUDINARY_CLOUD_NAME'),
        api_key       = env('CLOUDINARY_API_KEY'),
        api_secret    = env('CLOUDINARY_API_SECRET'),
        secure        = True,
        upload_preset = env('CLOUDINARY_UPLOAD_PRESET'),
        analytics     = False,
    )
    if 'PYTHONANYWHERE_DOMAIN' in os.environ:
        cloudinary.config(api_proxy='http://proxy.server:3128')

    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

    STRIPE_PUBLIC_KEY    = env('STRIPE_PUBLIC_KEY')
    STRIPE_SECRET_KEY    = env('STRIPE_SECRET_KEY')
    STRIPE_WEBHOOK_SECRET = env('STRIPE_WEBHOOK_SECRET')

    EMAIL_BACKEND     = env("EMAIL_BACKEND")
    EMAIL_HOST        = env("EMAIL_HOST")
    EMAIL_PORT        = env.int("EMAIL_PORT")
    EMAIL_USE_SSL     = env.bool("EMAIL_USE_SSL")
    EMAIL_USE_TLS     = env.bool("EMAIL_USE_TLS")
    EMAIL_HOST_USER   = env("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
    DEFAULT_FROM_EMAIL  = env("EMAIL_HOST_USER")

else:
    EMAIL_BACKEND     = 'django.core.mail.backends.locmem.EmailBackend'
    STRIPE_PUBLIC_KEY = 'pk_test_dummy'
    STRIPE_SECRET_KEY = 'sk_test_dummy'
    STRIPE_WEBHOOK_SECRET = 'whsec_dummy'

# ── Sitemap ──────────────────────────────────────────────────────────────────
SITEMAP_CACHE_TIMEOUT       = 60 * 60 * 24 * 30
SITEMAP_INCLUDE_ROOT        = True
SITEMAP_INCLUDE_SITEMAP_TAG = True
SITEMAP_INCLUDE_LASTMOD     = True
SITEMAP_INCLUDE_PRIORITY    = True
SITEMAP_INCLUDE_LOCATION    = True
SITEMAP_URL                 = '/sitemap.xml'