# Generated by Django 5.1.2 on 2024-10-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0002_macrame_together_delete_bijoux_maroquinerie_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrame',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maroquinerie',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='together',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
