# Generated by Django 5.1.2 on 2024-10-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0003_macrame_disponible_maroquinerie_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrame',
            name='type',
            field=models.CharField(choices=[('Murale', 'Murale'), ('Collier', 'Collier'), ('Bracelet', 'Bracelet'), ("Boucles d'oreilles", "Boucles d'oreilles"), ('Divers', 'Divers')], max_length=50),
        ),
    ]
