# Generated by Django 5.1.2 on 2024-10-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0005_alter_maroquinerie_type_alter_together_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maroquinerie',
            name='type',
            field=models.CharField(choices=[('Portefeuille, Porte carte', 'Portefeuille, Porte carte'), ('Blague à tabac', 'Blague à tabac'), ('Sac divers', 'Sac divers'), ('Ceinture', 'Ceinture'), ('Bijoux', 'Bijoux'), ('Collier chien', 'Collier chien'), ('Divers', 'Divers')], max_length=50),
        ),
        migrations.AlterField(
            model_name='together',
            name='type',
            field=models.CharField(choices=[('Murale', 'Murale'), ('Collier', 'Collier'), ('Bracelet', 'Bracelet'), ("Boucles d'oreilles", "Boucles d'oreilles"), ('Portefeuille, Porte carte', 'Portefeuille, Porte carte'), ('Blague à tabac', 'Blague à tabac'), ('Sac divers', 'Sac divers'), ('Ceinture', 'Ceinture'), ('Bijoux', 'Bijoux'), ('Collier chien', 'Collier chien'), ('Divers', 'Divers')], max_length=50),
        ),
    ]
