# Generated by Django 5.1.2 on 2025-01-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0006_alter_maroquinerie_type_alter_together_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrame',
            name='lien_image',
            field=models.URLField(default=''),
        ),
    ]
