# Generated by Django 5.1.2 on 2025-01-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0007_macrame_lien_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrame',
            name='lien_image',
            field=models.URLField(default='', max_length=20000),
        ),
    ]
