# Generated by Django 5.1.2 on 2025-02-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0010_macrame_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macrame',
            name='stock',
        ),
        migrations.AddField(
            model_name='maroquinerie',
            name='lien_image1',
            field=models.URLField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='maroquinerie',
            name='lien_image2',
            field=models.URLField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='maroquinerie',
            name='lien_image3',
            field=models.URLField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='maroquinerie',
            name='lien_image4',
            field=models.URLField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='together',
            name='lien_image1',
            field=models.URLField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='together',
            name='lien_image2',
            field=models.URLField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='together',
            name='lien_image3',
            field=models.URLField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='together',
            name='lien_image4',
            field=models.URLField(default='', max_length=20000),
        ),
    ]
