# Generated by Django 5.1.2 on 2025-02-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0011_remove_macrame_stock_maroquinerie_lien_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('Macrame', 'Macrame'), ('Maroquinerie', 'Maroquinerie'), ('hybride', 'hybride'), ('entretien', 'entretien')], max_length=50)),
                ('type', models.CharField(choices=[('Murale', 'Murale'), ('Collier', 'Collier'), ('Bracelet', 'Bracelet'), ("Boucles d'oreilles", "Boucles d'oreilles"), ('Portefeuille, Porte carte', 'Portefeuille, Porte carte'), ('Blague à tabac', 'Blague à tabac'), ('Sac divers', 'Sac divers'), ('Ceinture', 'Ceinture'), ('Bijoux', 'Bijoux'), ('Collier chien', 'Collier chien'), ('Divers', 'Divers')], max_length=50)),
                ('ornement', models.CharField(max_length=200)),
                ('prix', models.FloatField(default=0.0)),
                ('lien_image1', models.URLField(default='', max_length=20000)),
                ('lien_image2', models.URLField(default='', max_length=20000)),
                ('lien_image3', models.URLField(default='', max_length=20000)),
                ('lien_image4', models.URLField(default='', max_length=20000)),
                ('disponible', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Macrame',
        ),
        migrations.DeleteModel(
            name='maroquinerie',
        ),
        migrations.DeleteModel(
            name='Together',
        ),
    ]
