# Generated by Django 5.1.2 on 2025-02-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0012_allproducts_delete_macrame_delete_maroquinerie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='lien_image1',
            field=models.URLField(blank=True, default='', max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='lien_image2',
            field=models.URLField(blank=True, default='', max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='lien_image3',
            field=models.URLField(blank=True, default='', max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='lien_image4',
            field=models.URLField(blank=True, default='', max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='ornement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
