# Generated by Django 5.1.2 on 2025-02-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0013_alter_allproducts_lien_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='categorie',
            field=models.CharField(choices=[('Macrame', 'Macrame'), ('Maroquinerie', 'Maroquinerie'), ('Hybride', 'Hybride'), ('Entretien', 'Entretien')], max_length=50),
        ),
    ]
