# Generated by Django 5.1.4 on 2025-02-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0016_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
