# Generated by Django 5.1.2 on 2025-02-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0017_alter_allproducts_disponible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='section_id',
            new_name='session_id',
        ),
    ]
