# Generated by Django 5.1.2 on 2025-02-21 09:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0019_allproducts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True),
        ),
    ]
