# Generated by Django 5.1.2 on 2025-02-21 10:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0020_alter_allproducts_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allproducts',
            old_name='image',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='allproducts',
            name='lien_image1',
        ),
        migrations.RemoveField(
            model_name='allproducts',
            name='lien_image2',
        ),
        migrations.RemoveField(
            model_name='allproducts',
            name='lien_image3',
        ),
        migrations.RemoveField(
            model_name='allproducts',
            name='lien_image4',
        ),
        migrations.AddField(
            model_name='allproducts',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allproducts',
            name='image3',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allproducts',
            name='image4',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True),
        ),
    ]
