# Generated by Django 5.1.2 on 2025-03-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0021_rename_image_allproducts_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='categorie',
            field=models.CharField(choices=[('Hybride', 'Hybride'), ('Macrame', 'Macrame'), ('Maroquinerie', 'Maroquinerie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='type',
            field=models.CharField(choices=[('Blague à tabac', 'Blague à tabac'), ("Boucles d'oreilles", "Boucles d'oreilles"), ('Bracelet', 'Bracelet'), ('Ceinture', 'Ceinture'), ('Chaine de corps', 'Chaine de corps'), ('Chevillère', 'Chevillère'), ('Collier', 'Collier'), ('Collier chien', 'Collier chien'), ('Divers', 'Divers'), ('Entretien', 'Entretien'), ('Murale', 'Murale'), ('Portefeuille, Porte carte', 'Portefeuille, Porte carte'), ('Sac divers', 'Sac divers')], max_length=50),
        ),
    ]
