# Generated by Django 5.1.2 on 2025-03-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0022_allproducts_description_alter_allproducts_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allproducts',
            name='ornement',
        ),
    ]
