# Generated by Django 5.1.2 on 2025-03-10 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0023_remove_allproducts_ornement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
