# Generated by Django 5.1.2 on 2025-03-13 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0025_alter_cart_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Ex : 2024-06-01', max_length=20, unique=True)),
                ('content', models.TextField(help_text='Texte complet des CGV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='cgv_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='cgv_accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='page_vente.cgv'),
        ),
    ]
