# Generated by Django 5.1.2 on 2025-03-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0026_cgv_cart_cgv_accepted_at_cart_paid_cart_cgv_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='en_attente_dans_panier',
            field=models.BooleanField(default=False),
        ),
    ]
