# Generated by Django 5.1.2 on 2025-03-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0027_allproducts_en_attente_dans_panier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookiesPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Ex : 2024-06-01', max_length=20, unique=True)),
                ('content', models.TextField(help_text='Texte complet des cookies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
