# Generated by Django 5.1.2 on 2025-03-14 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0029_legalmentions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LegalMentions',
            new_name='LegalMention',
        ),
    ]
