# Generated by Django 5.1.2 on 2025-03-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0032_cart_cgv_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
