# Generated by Django 5.1.2 on 2025-03-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0033_cart_cart_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
