# Generated by Django 5.1.2 on 2025-03-16 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0034_cart_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgv',
            name='version',
            field=models.CharField(help_text='Ex : 2024-06-01', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Format de version incorrect, utilisez YYYY-MM-DD.', regex='^\\d{4}-\\d{2}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='cookiespolicy',
            name='version',
            field=models.CharField(help_text='Ex : 2024-06-01', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Format de version incorrect, utilisez YYYY-MM-DD.', regex='^\\d{4}-\\d{2}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='legalmention',
            name='version',
            field=models.CharField(help_text='Ex : 2024-06-01', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Format de version incorrect, utilisez YYYY-MM-DD.', regex='^\\d{4}-\\d{2}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='version',
            field=models.CharField(help_text='Ex : 2024-06-01', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Format de version incorrect, utilisez YYYY-MM-DD.', regex='^\\d{4}-\\d{2}-\\d{2}$')]),
        ),
    ]
