# Generated by Django 5.1.2 on 2025-03-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0036_cgv_content_en_cgv_content_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgv',
            name='content',
            field=models.TextField(blank=True, help_text='Texte complet des CGV', null=True),
        ),
        migrations.AlterField(
            model_name='cookiespolicy',
            name='content',
            field=models.TextField(blank=True, help_text='Texte complet des cookies', null=True),
        ),
        migrations.AlterField(
            model_name='legalmention',
            name='content',
            field=models.TextField(blank=True, help_text='Texte complet des mentions légales', null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=models.TextField(blank=True, help_text='Texte complet de la politique de confidentialité', null=True),
        ),
    ]
