# Generated by Django 5.1.2 on 2025-03-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0037_alter_cgv_content_alter_cookiespolicy_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cgv',
            name='content',
        ),
        migrations.RemoveField(
            model_name='cookiespolicy',
            name='content',
        ),
        migrations.RemoveField(
            model_name='legalmention',
            name='content',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='content',
        ),
    ]
