# Generated by Django 5.1.2 on 2025-05-23 12:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0038_remove_cgv_content_remove_cookiespolicy_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='image5',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allproducts',
            name='image6',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True),
        ),
    ]
