# Generated by Django 5.1.2 on 2025-06-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0039_allproducts_image5_allproducts_image6'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
