# Generated by Django 5.1.2 on 2025-06-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0040_allproducts_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='description',
            field=models.CharField(blank=True, max_length=135, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='nom',
            field=models.CharField(max_length=58),
        ),
    ]
