# Generated by Django 5.1.2 on 2025-06-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0041_alter_allproducts_description_alter_allproducts_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='sur_commande',
            field=models.BooleanField(default=False),
        ),
    ]
