# Generated by Django 5.1.2 on 2026-02-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0042_allproducts_sur_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
    ]
